package Eden;

public class Graphics {
    //todo i would suggest to make graphics an abtract class and implement each of the specific grapics in child clases. This makes it easier to maintain.
    void heart() {
        System.out.println("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNNNNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNK0OkxddddodddxkOKXNWMMMMMMMMMMMMMMMWNKOkxdollccccllodxO0XWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKkdl:;;,,,,,,,,,,,,,;cldOXWMMWWWWMMWWXOdl:;,,,,,,,,,,,,,,,,;:ox0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXko:;;,,,,,,,,,,,,,,,,,,,,,;cxKWWWWMMWKxc;;;,,,,,,,,,,,,,,,,,,,,,,;lkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXxc::cc:,,',,,;;;;;;;,,,,,,,,,,,:xXWWWNkc:cc:,,,,,,,;;;;;;;;;;,,,,,,,,,ckXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNOl:cldxdl;,,,,;:::::::::;;;,,,,,,,;lO0Oo::lol:,,,,,;;::ccc::::::;;;,,,,,,;l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXx::ldkOOxc;,,,,;;:::ccccc:::;;,,,,,,,;;;:codoc;,,,,;;::cccccccccc:::;;,,,,,,:kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd::ldkOOxl;,,,,,;;:::ccccccc:::;;,,,,,,,,;:cc:;,,,,,;:::ccccccccccccc::;;,,,,,:kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx:;:ldkkdl;,,,,,,,;;:::cccccccc::;;,,,,,,,,,,;,,,,,,;;::ccccccllllcccc::;;,,,,,,:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOc:::clool:,,,,,,,,,;;:::ccccccccc::;;,,,,,,,,,,,,,,;;:::ccccccllllcccc::;;,,,,,,,lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXo;clccccc:,,,,,,,,,,,;;;::ccccccccc::::;;;;;;;,,,,,;;:::cccccccccccccc:::;,,,,,,,,;kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c:ldolc:;,,,,,,,,,,,,,,;;;::cccccccccccc:::::;;;;;;;:::::ccccccccccc:::;;,,,,,,,,,,oXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk::oxxdl:;,,,,,,,,,,,,,,,,;;;::ccccccccccccc:::;;;;;:::::::::::::::::;;;;,,,,,,,,,,,lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk::lodol:;,,,,,,,,,,,,,,,,,,,;;;:::ccccccccc::::;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,cKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:,;;;:::;;,,,,,,,,,,,,,,,,,,,,,;;;;;::::::::;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'lXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKc,,,,;;;;;;,,,;;;;;;;;,,,,,,,,,,,,,,,,,;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''''dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNx,',,;;;;;;;,;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''':0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKl,,,;;:::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'',xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:,,;;::::::;;;;;:::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,'''oXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNk:,;;;:::::::::::::::::::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;,,,,,,''''oXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:,;;;::::::::::::::::::::::::::::::::::::::::::::::::::;;;;;;;;;;;;;,,,''',oXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l,,;;;:::::::::::::::::::::::::::::::::::::::::::::::::;;;;;;;;;;;,,,''.,xNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo;,;;;;;:::::::::::::::::::::::::::::::::::::::::::::;;;;;;;;;;;,,,''':OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNOc;,;;;;;:::::::::::::::::::::::::::::::::::::::::;;;;;;;;;;;,,,,'',oXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXx:,,;;;;;;;;;;;;::::::::::::::::::::::::::::;;;;;;;;;;;;;;,,,'''l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd:,;;;;;;;;;;;;;:::::::::::::::::::::::;;;;;;;;;;;;;;,,,''',cONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWKdc,,;;;;;;;;;;;;;:::::::::::::;;;;:;;;;;;;;;;;;;;,,,,'',cONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl;,,;;;;;;;;;;;;;;:::::::;;;;;;;;;;;;;;;;;;,,,,,'';o0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0d:,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,'',cxKWWMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXko:,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,'':o0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXko:,,;;;;;;;;;;;;;;;;;;;;;;;;,,,,',:oOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNKko:;,;;;;;;;;;;;;;;;;;;,,,,'';okXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWXko:,,;;;;;;;;;;;;;,,,,';lkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWKko:,;;;;;;;;;;,,',cxKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxl;;;;;;;,,,:o0NMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0dc;;,,;lkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXOkxk0NWWMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
    }

    void stranger1() {
        System.out.println("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkl:,....,ckNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0;           :0MMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk.             ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO'              .dMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,                oWMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.               .OMMMMMMMMMMMMMMMMXoxWMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.              .lXMMWWWMMMMMMMMMWMK,'OMMMX0NMM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc             .cKWWWNNWMMWMMXOOKNWNc :XMK;,0MM\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMWWNK0kxo.             '0WWNWWMMMMWWNOl,.,lkc .lx, ;KMM\n" +
                "MMMWXKNMMMMWWMMMMMWNKOxoc:,'..                 .oNNNWMMMWNNWWk,:d:      ..,oKWMM\n" +
                "MMMMXO0KXNNKXWWWXxc'.                          ;0NNWWXNNXXNWMk. ..     .dXNWMMMM\n" +
                "MMMWX000OOOkdxd:.                              .cOXXX000XWMMM0,     ..:kWWWMMMMM\n" +
                "MMMWNNNXXK00dc'                                  .dKXOxONWMMM0'  .:kKXWMMMMMMMMM\n" +
                "WNXXXXXXXXNNX0o.                                   ':lkKNWWNXl.  .kMMMMMMMMMMMMM\n" +
                "WXXXNNWWWWMWN0d.                                     ':xXNX0d'   'ONWMMMMMMMMMMM\n" +
                "MMMMMMMMMMWX0k:                                        .;lol.    .dKWMMMMMMMMMMM\n" +
                "MMMMMWWNNNXKK0:                                          .'.     'k0KNMMMMMMMMMM\n" +
                "MMMMMWWNNNNWWWk;.                                                :00OKWMMMMMMMMM\n" +
                "MMMMMMMMMMWWWWNKx:,.                                            .dWMMMMWMMMMMMMM\n" +
                "MMMMMMWWWWWNWWMMWNNKx,                                          .kMMMMMMMMMMMMMM\n" +
                "MMMMMMWWWWMMMMMMWKK0K0l,.                                       :XMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMNKXMMMMX00O0Ox:                                      ,0WMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMWK00KNWWNK0kOxl.                                     oWMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMNKK00NWXOkxl'                                    :KMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMWMMWWMNK0KNNOol;.                         '.      .xNMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMWWWWMMMMWXKKXo,'.                       'dKd.     'OWMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMWWMMMMMMWWWNXKO;                         oWO,       .:0WMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMWXXNMMMWWWNXXXk.                         ,l. .;lxkkl. ,KMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMWX0XNW0k000OOd'                         ...oXNNWMWk. '0MMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMWNXNNKKWXkc.                           'dXMW0oc:. 'xWMMMMMMMMMMMMMMM\n" +
                "MMMMMWWWMMMMMMWNXXXXWXo.                          cKX0XWMKkddkXWMMMMMMMMMMMMMMMM\n" +
                "MMMMWWNNNWWMMMMMWNX0XO,                          .xWMWNNMMMWMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMWWNNWWNNWWNKO:                           'OWMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMWWNXXKd.                           ;KWMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMWWWNc                           .dNWMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMMK,                           ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMMMMMWd.                           oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n");
    }
}